import { createThemeContract } from '@vanilla-extract/css';

export const vars = createThemeContract({
  color: {
    primitive: {
      charcoal: {
        50: null,
        100: null,
        200: null,
        300: null,
        400: null,
        500: null,
        600: null,
        700: null,
        800: null,
        900: null,
        950: null,
      },
      gold: {
        50: null,
        100: null,
        200: null,
        300: null,
        400: null,
        500: null,
        600: null,
        700: null,
        800: null,
        900: null,
        950: null,
      },
      sage: {
        50: null,
        100: null,
        200: null,
        300: null,
        400: null,
        500: null,
        600: null,
        700: null,
        800: null,
        900: null,
        950: null,
      },
      terracotta: {
        50: null,
        100: null,
        200: null,
        300: null,
        400: null,
        500: null,
        600: null,
        700: null,
        800: null,
        900: null,
        950: null,
      },
    },
    semantic: {
      brand: {
        primary: null,
        primaryHover: null,
        primaryActive: null,
        accent: null,
        accentHover: null,
        accentActive: null,
      },
      background: {
        base: null,
        subtle: null,
        muted: null,
        elevated: null,
        overlay: null,
      },
      foreground: {
        primary: null,
        secondary: null,
        tertiary: null,
        muted: null,
        onBrand: null,
        accent: null,
      },
      border: {
        default: null,
        strong: null,
        subtle: null,
        accent: null,
      },
      success: {
        base: null,
        hover: null,
        subtle: null,
        text: null,
        border: null,
      },
      error: {
        base: null,
        hover: null,
        subtle: null,
        text: null,
        border: null,
      },
      warning: {
        base: null,
        hover: null,
        subtle: null,
        text: null,
        border: null,
      },
      info: {
        base: null,
        hover: null,
        subtle: null,
        text: null,
        border: null,
      },
    },
  },
  gradient: {
    background: {
      subtle: null,
      muted: null,
      warm: null,
    },
    brand: {
      primary: null,
      accent: null,
      hero: null,
      subtle: null,
    },
    overlay: {
      dark: null,
      light: null,
    },
    mesh: {
      warm: null,
      subtle: null,
    },
    shimmer: {
      gold: null,
      light: null,
    },
    text: {
      gold: null,
      subtle: null,
      hero: null,
    },
    success: {
      subtle: null,
      base: null,
    },
    error: {
      subtle: null,
      base: null,
    },
    warning: {
      subtle: null,
      base: null,
    },
  },
  space: {
    0: null,
    1: null,
    2: null,
    3: null,
    4: null,
    5: null,
    6: null,
    8: null,
    10: null,
    12: null,
    16: null,
    20: null,
    24: null,
    32: null,
  },
  shadow: {
    none: null,
    sm: null,
    base: null,
    md: null,
    lg: null,
    xl: null,
    '2xl': null,
    inner: null,
  },
  radius: {
    none: null,
    sm: null,
    base: null,
    md: null,
    lg: null,
    xl: null,
    '2xl': null,
    '3xl': null,
    full: null,
  },
  transition: {
    duration: {
      fast: null,
      base: null,
      slow: null,
      slower: null,
    },
    easing: {
      linear: null,
      in: null,
      out: null,
      inOut: null,
    },
  },
});
