import { createThemeContract } from '@vanilla-extract/css';

export const vars = createThemeContract({
  color: {
    brand: {
      50: null,
      100: null,
      200: null,
      300: null,
      400: null,
      500: null,
      600: null,
      700: null,
      800: null,
      900: null,
      950: null,
    },
    gray: {
      50: null,
      100: null,
      200: null,
      300: null,
      400: null,
      500: null,
      600: null,
      700: null,
      800: null,
      900: null,
      950: null,
    },
    accent: {
      purple: null,
      pink: null,
      orange: null,
      green: null,
    },
    semantic: {
      success: null,
      warning: null,
      error: null,
      info: null,
    },
  },
  space: {
    px: null,
    0: null,
    0.5: null,
    1: null,
    1.5: null,
    2: null,
    2.5: null,
    3: null,
    3.5: null,
    4: null,
    5: null,
    6: null,
    7: null,
    8: null,
    9: null,
    10: null,
    12: null,
    16: null,
    20: null,
    24: null,
    32: null,
    40: null,
    48: null,
    56: null,
    64: null,
  },
  shadow: {
    none: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    '2xl': null,
    inner: null,
  },
  radius: {
    none: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    '2xl': null,
    '3xl': null,
    full: null,
  },
  transition: {
    duration: {
      fast: null,
      base: null,
      slow: null,
      slower: null,
    },
    easing: {
      ease: null,
      easeIn: null,
      easeOut: null,
      easeInOut: null,
      linear: null,
      spring: null,
    },
  },
});

